# Generated by Django 5.0.14 on 2026-07-02 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Nivel de dificultad de la categoria (1-5)', unique=True)),
                ('premio', models.IntegerField(default=0, help_text='Premio en puntos por acertar una pregunta de esta categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda_actual', models.IntegerField(default=1, help_text='Ronda/Nivel en el que está respondiendo')),
                ('puntaje', models.IntegerField(default=0, help_text='Puntaje toatal acumulado hasta ahora')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('GANADA', 'Ganada (Ronda 5 superada)'), ('RETIRADO', 'Retiro voluntario del jugador'), ('PERDIDA', 'Perdida (Respuesta incorrecta)')], default='EN_PROGRESO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='trivia.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='trivia.pregunta')),
            ],
        ),
    ]
